alter table RTCABO_PRODUCT add constraint FK_RTCABO_PRODUCT_CATEGORY foreign key (CATEGORY_ID) references RTCABO_PRODUCT_CATEGORY(ID);
create index IDX_RTCABO_PRODUCT_CATEGORY on RTCABO_PRODUCT (CATEGORY_ID);
